### ISSUE TITLE
script.js viene eseguito prima del caricamento del json in calls.js

### ISSUE THREAD

**Issue by jenkin** [DnlWD/AltalenantePorfolio#1]
[Questo commento](https://github.com/DnlWD/AltalenantePorfolio/blob/cd86342959d112694116f3a5a15f9bb21bcc62b5/src/js/script.js#L1) è sbagliato. Se vuoi attaccare una funzione al click **dopo** aver caricato i dati devi mettere il contenuto di [script.js](https://github.com/DnlWD/AltalenantePorfolio/blob/developer/src/js/script.js) **dentro** la callback in [calls.js](https://github.com/DnlWD/AltalenantePorfolio/blob/developer/src/js/calls.js).

Poi funziona lo stesso, perché in script.js in realtà non usi i dati caricati dal json, ti limiti a selezionare con jquery delle classi al click sui pulsanti. Ma il commento rimane sbagliato... :smile:

**Comment by DnlWD** [comment]
Si era solo un commento per far capire ad Arianna cosa era il document ready in generale poi mi sono scordato di rimuoverlo
