### ISSUE TITLE
Pulsante di chiusura della modale del progetto sostanzialmente invisibile

### ISSUE THREAD

**Issue by jenkin** [DnlWD/AltalenantePorfolio#2]
La modale del singolo progetto occupa l'intero viewport, sembra quasi che carichi una nuova pagina. La `x` in alto a destra è praticamente invisibile, ci ho messo un bel po' a trovarla e capire quindi come tornare alla home con tutti i progetti... :smile:

**Comment by DnlWD** [comment]
Si l'avevo notato, ci lavorerò sopra
